### ISSUE TITLE
Remove the App Compat Library from Android and save over 5.5MB

### ISSUE THREAD

**Issue by GrantOjanen** [cerberusxdev/cerberus#109]
Just comment out the one line that imports the app compat library, and the base size of a game will go from 6.25MB to 668KB (based on the bouncy aliens example when installed on my phone).

There should probably be a way to include it again using the config.cxs file.

https://github.com/cerberusxdev/cerberus/blob/develop/targets/android/template/gradletemplate/app/build.gradle#L45

Dead code really gets on my nerves. ha ha

What do you think of this? I'd like to do a PR for this.

**Comment by MikeHart66** [comment]
That needs to be well tested before removing it.
