### ISSUE TITLE
Add Linux to The Desktop target.cerberusdoc

### ISSUE THREAD

**Issue by GrantOjanen** [cerberusxdev/cerberus#111]
I'd like to add a link for Linux on "The Desktop target.cerberusdoc" to the installation and build requirements guide. https://www.cerberus-x.com/community/index.php?threads/install-and-build-requirements-for-linux-includes-raspbery-pi-updated.741/

Also move up the "Notes" section, so that it is with the rest of the Windows information.

As a beginner these changes would have saved me a bit of time.

File:
https://github.com/cerberusxdev/cerberus/blob/develop/docs/cerberusdoc/Target%20SDKs/The%20Desktop%20target.cerberusdoc

Proposed Changes:
https://github.com/GrantOjanen/cerberus/commit/776cf43e7e456faeb1a080a08473184b36087709#diff-aa190177179f157f4f3d36e69263ff3db9031c668c37f4f74c9075cbd0a12b48

**Comment by MikeHart66** [comment]
Philipp is currently working on restructuring the docs. Thanks for the heads up.

**Comment by cerberusxdev** [comment]
Moving this to the forum
