### ISSUE TITLE
Completely hide console on HTML with #HTML5_CONSOLE_SHOW

### ISSUE THREAD

**Issue by GrantOjanen** [cerberusxdev/cerberus#113]
When setting #HTML5_CONSOLE_SHOW to False it leaves a blank spot where the console would have been. Also the console is shown for a split second when the game first starts.

https://github.com/GrantOjanen/cerberus/commit/67bd8420951bc203468579427f666a1bc91b3c72#diff-0ca17d8b1de08089e88e6fed11442b345e8dedce835e535e7020906f0c438350

**Comment by MikeHart66** [comment]
When you don't set the size of the Canvas and might let it scale, of course there is a blank spot. 640x480 can only be that big unscaled.

**Comment by cerberusxdev** [comment]
Closing issues so there is only one place, the forum.
