### ISSUE TITLE
Setting MinGW desktop as a target on Linux. 

### ISSUE THREAD

**Issue by MetalMaxMX** [cerberusxdev/cerberus#137]
I have a question/documentation issue and I am not seeing it anywhere so I'd like to know. When you run a binary of Cerberus X on any Linux host, the available target options are usually Android, HTML5 and the Linux target, both debug and release. However, according to this topic here https://www.cerberus-x.com/community/index.php?threads/crosscompiling.1493/

It seems like crosscompiling from one platform to another is possible. As the title of my post implies, I am seeing if compiling from Linux to Windows through MinGW could be possible. As per the official site at (https://mingw.osdn.io/) it is possible to build and run MinGW on a Linux host and generate binaries from there. As Cerberus X already has MinGW support, could this be extended to apply to Linux as well? So that a workflow of: HTML5, mobile, Linux and Windows could be there in one go? Of course as long as the user has provided their own MinGW compiler.

**Comment by dawlane** [comment]
It is possible. I did it over ten years with Monkey X, the forerunner of Cerberus. But it got rejected by the author of Monkey X. Something about not being able to do any profiling, or something.

The trick is that you have to change the transcc code into thinking that it's running on a Windows host and set the correct name name for the Linux port of MinGW. You will of course have to have WINE installed to run the resulting binaries.

**Comment by MetalMaxMX** [comment]
Oh, awesome that it is possible! I see, so it was transcc code that needed to be modified and all. Are there any more detailed instructions on the documentation (or a step-by-step) on how to handle this? In case I end up getting build errors or so. (or a script at least)

**Comment by dawlane** [comment]
You will not find anything in the documentation on how to do it. You have to look at how the transcc works to achieve what you wish to do. You would find it much easier using Cerberus on Linux to generated the C++ files and make a few changes to the gcc_winnt makefiles in the .build directory to do a cross compilation.

**Comment by MetalMaxMX** [comment]
Well, makes sense. That's a good approach as well, and is certainly much easier than the rest. I think with this enough I might have enough info to go on, feel free to close the issue. (though if at some point documentation on this could be added somewhere, or a reference. That would be nice)

**Comment by dawlane** [comment]
The one thing you would need to be aware of when compiling Cerberus C++ directly from source to do cross compilation, is that you cannot use the HOST environment variable to filter code to build for the different targets. You would have to use the HostOS function in the os module. This would add to the size of the binary, but with a bit of searching and editing, you can replace the code blocks to defines.

**Comment by MetalMaxMX** [comment]
What do you mean by that in more detail? As in, one needs to change bash environment variables and exports before attempting this?

**Comment by dawlane** [comment]
As in you cannot use the Cerberus HOST environment variable.
https://www.cerberus-x.com/cxDocs/Programming_Language%20reference.html#preprocessor

**Comment by MetalMaxMX** [comment]
Ah, I see what you mean. This probably has to be disabled right away or something, thanks! 
(Though at this point I am convinced that is probably easier to use Wine to build things at this point)

**Comment by dawlane** [comment]
No need to disable anything if you:
Use a custom Cerberus pre processor directive as stated in the documentation.
Use Cerberus on Linux to generate the required .build, then use the makefile in the gcc_winnt with the required changes.

**Comment by MetalMaxMX** [comment]
Thanks! I understand now a bit better the architecture behind this. Specially after reading the documentation. 
If I end up running into additional issues potentially caused by the pre-processors or the gcc_winnt makefiles, I may make a post on the forums to do so. I'll be closing this issue for now as those two methods were what I wanted to know. 

Once again, thanks!
MetalMaxMX.
