### ISSUE TITLE
Mojo2 doesn't work anymore after changes to Transcc

### ISSUE THREAD

**Issue by MikeHart66** [cerberusxdev/cerberus#144]
Hi folks,

just want to leave a note here that any mojo2 example doesn't work anymore after transcc got updated lately. No matter which platform I tried.

Cheers
Michael

**Comment by dawlane** [comment]
I've nailed it down.
It was the change I made to try to use the record separator (U001E)  in modules/trans/preprocessor.cxs
I will have to have a look at what's needed to be done to get the shader to work with that if possible possible.
For the time being, change:
If var And Not val.StartsWith( "~u001E" ) val="~u001E"+val
Back to.
If var And Not val.StartsWith( "|" ) val="~|"+val

Sorry about.

**Comment by PhilMoe** [comment]
This should be fixed with your PR https://github.com/cerberusxdev/cerberus/pull/145 
Thank you!

**Comment by PhilMoe** [comment]
This should be fixed with your PR https://github.com/cerberusxdev/cerberus/pull/145
Thank you!
