### ISSUE TITLE
Mojo2 color doesnt allow floats if you import mojo2.graphics first

### ISSUE THREAD

**Issue by pantson** [cerberusxdev/cerberus#79]
If you import mojo2, #COLOR_USE_NORMALISED_COMPONENTS is inititalised which allows floats in Color. If you import mojo2.graphics,  #COLOR_USE_NORMALISED_COMPONENTS  isnt initialised and floats arent allowed. It might not be a bug and import mojo2 might be the documented way, rather than import mojo2.graphics.
For my project I didnt want to include mojo.audio, but I can see most game projects do want to include all mojo components 

    Import mojo2.graphics
    col = New Color(Rnd(),Rnd(),Rnd())
    ' always 0
    Print col.r

**Comment by Holzchopf** [comment]
It's actually kinda documented in the code itself... In mojo2.graphics:

```
' 20190117 - Holzchopf
' Color class support
'#COLOR_USE_NORMALISED_COMPONENTS = True - this must be done in mojo2.cxs, don't ask why
Import mojo.color
```

If #COLOR_USE_NORMALISED_COMPONENTS is initialised in mojo2.graphics, it doesn't get passed to mojo.color - seems like a bug in trans (I'm pretty sure I reported that one in the forums... 🤔). I tried to look into it myself, but didn't find a fix...

However, back to the float components: You can trigger it yourself in your code file, before importing. E.g.:
```
#COLOR_USE_NORMALISED_COMPONENTS = True
Import mojo2.graphics
Function Main()
	Local col:Color = New Color(Rnd(),Rnd(),Rnd())
	Print col.r
End
```

It looks like it could work too if `#COLOR_USE_NORMALISED_COMPONENTS = True` is set in mojo2 as well as mojo2.graphics - BUT I'll have to check some more cases before I fix and commit that in CX. I made a note to look into it. Until then, this report stays open 😉

**Comment by pantson** [comment]
It was because of your comments in the code that made me realise why my code didnt work at the point ;-) 
thanks for looking into this
