### ISSUE TITLE
Replace Android JNI with pure Java

### ISSUE THREAD

**Issue by GrantOjanen** [cerberusxdev/cerberus#81]
Why are the native libraries included in the Android target used instead of Java? They seem to only contain two small methods for parsing numbers from strings. It would be nice to see it be pure Java on Android, so it'll be compatible with any possible processor architecture that comes out in the future.

https://github.com/MikeHart66/cerberus/blob/develop/targets/android/template/langutil/jni/langutil.c

**Comment by GrantOjanen** [comment]
Replacing the two native methods with Java's build in `Integer.parseInt()` and `Float.parseFloat()` doesn't seem to cause any problems with my test project. Rendering numbers in text worked. I don't understand why the native code exists.

**Comment by MikeHart66** [comment]
I can't tell you why the original creator of Monkey X did it this way. Definitely something that has to be looked into.

**Comment by GrantOjanen** [comment]
LangUtil.java
```
package com.cerberus;

public class LangUtil{

	public static int parseInt( String str ) {
		return Integer.parseInt(str);
	}
	
	public static float parseFloat( String str ) {
		return Float.parseFloat(str);
	}
}
```
