### ISSUE TITLE
API to Get Names and Axis/Button Count of Game Controllers

### ISSUE THREAD

**Issue by GrantOjanen** [cerberusxdev/cerberus#82]
Being able to get the display name and button/axis count of a controller would be really nice to have. It should be pretty easy to put in.

GLFW: glfwGetJoystickName(), glfwGetJoystickButtons(), glfwGetJoystickAxes()
HTML5: gamepad.id, gamepad.buttons.length, gamepad.axes.length
Android: InputDevice.getName(), It looks like Cerberus uses hard coded button/axis counts on Android.

**Comment by pantson** [comment]
looking at the above enhancement starting with GLFW. Extending PollJoystick.. this should then work across all targets
![joy](https://user-images.githubusercontent.com/35967917/75609966-1300b900-5b05-11ea-8d8a-0d1e52d808b3.png)
