### ISSUE TITLE
Desktop target docs incorrect - VS2013 vs VS2017/2019?

### ISSUE THREAD

**Issue by Arantor** [cerberusxdev/cerberus#90]
The Desktop target for Windows talks about using VS Express 2013 with Update 4... at time of writing Update 5 is the latest, but if you manage to find and download VS Express 2013, builds will fail.

The project\project.buildv2020-05-09\glfw3\msvc\CerberusGame.vcxproj file generated will refer to the 141 build dependencies of MSBuild which is... VS2017? As these don't get installed with VS2013, there's a bit of headscratching involved.

Not sure which is the preferred route here, whether to document how to fix the project file so VS2013 works (easy enough, in the vcxproj file, just find `<PlatformToolset>` in both the debug and release builds and replace with v120 instead of v141) or, probably, the better route to update the docs to suggest whichever version of VS Express/Community/whatever is the build the CX devs themselves are using.

**Comment by MikeHart66** [comment]
Thanks for the report, the docs will be fixed. I suggest 2017.

**Comment by MikeHart66** [comment]
Docs now mention and link to Visual Studio Community 2017 version.
